server:
  port: 8080

#Configuracion para registrarse en eureka.
spring:
  eureka:
    client:
      service-url:
        defaultZone:  http://eureka-service:8761/eureka

  cloud:
    gateway:
      routes:
        - id: movieRoute
          uri: lb://movie-service
          predicates:
            - Path=/movie/**
          filters:
            - name: CircuitBreaker
              args:
                name: movieService
                fallbackUri: forward:/fallback/movie
        - id: catalogRoute
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**
          filters:
            - name: CircuitBreaker
              args:
                name: catalogService
                fallbackUri: forward:/fallback/catalog
        - id: seriesRoute
          uri: lb://serie-service
          predicates:
            - Path=/serie/**
          filters:
            - name: CircuitBreaker
              args:
                name: serieService
                fallbackUri: forward:/fallback/serie

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: API Gateway