server:
  port: 8084

spring:
  rabbitmq:
    username: guest
    password: guest
    host: rebbitmq
    port: 5672

  data:
    mongodb:
      authentication-database: admin
      username: admin
      database: tp_final
      port: 27017
      host: localhost

queue:
  movie:
    name: Movie
  serie:
    name: Serie

#Exponiendo los endpoints de Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always

#Configurando el Circuit-breaker para los llamados http usando los clientes feign de Movies y Series
resilience4j:
  circuitbreaker:
    instances:
      catalog:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true


#Configuracion del mecanismo de reintentos
  retry:
    instances:
      catalog:
        maxAttempts: 3
        waitDuration: 1000
        retryExceptions[0]: feign.FeignException$InternalServerError

info:
  app:
    name: Catalog Service
    description:  Service for Catalog
    versioon: 0.0.1 SNAPSHOT