server:
  port: 8082

spring:
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq
    port: 5672

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;
    username: sa
    password: sa
  sql:
    init:
      data-locations: classpath:import.sql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

queue:
  movie:
    name: Movie

#Exponiendo los endpoints de Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
      
info:
  app:
    name: Movie Service
    description:  Service for movies
    versioon: 0.0.1 SNAPSHOT
