server:
  port: 8086

spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: tp_final
      port: 27017
      host: localhost

info:
  app:
    name: Serie Service
    description:  Service for Series
    versioon: 0.0.1 SNAPSHOT

