server:
  port: 8086

#Configuracion para registrarse en eureka.
spring:
  eureka:
    client:
      service-url:
        defaultZone:  http://eureka-service:8761/eureka


  data:
    mongodb:
      authentication-database: admin
      username: admin
      database: tp_final
      port: 27017
      host: localhost

#Exponiendo los endpoints de Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app:
    name: Serie Service
    description:  Service for Series
    versioon: 0.0.1 SNAPSHOT

