server:
  port: 8086

spring:
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq
    port: 5672

  data:
    mongodb:
      authentication-database: admin
      username: admin
      database: tp_final
      host: mongodb
      port: 27017


queue:
  serie:
    name: Serie

#Exponiendo los endpoints de Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app:
    name: Serie Service
    description:  Service for Series
    versioon: 0.0.1 SNAPSHOT

