#Configurando el servidor.
server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/royalejandro09/spring-cloud-server
          searchPaths: checkFinalBackend

#Indicando la ruta de eureka para registrarse como cliente:
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
