#Configurando el servidor.
server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/royalejandro09/Microservices-Architecture
          #searchPaths: checkFinalBackend

#Indicando la ruta de eureka para registrarse como cliente:
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#Informacion de nuestro config-service.
info:
  app:
    name: CONFIG-SERVICE
    description: Config-server
    version: 1.0.0